### PR TITLE
chore: switch to zwave-js@6.0.0 #23

### LINKED ISSUE #23: [feat] Better zwave-js logging options
Is there a way to speficy the location of the log file? @AlCalzone

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #23 #128

Needs zwave-js@6.0.0

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]

**Comment by blhoward2** [comment]
When starting up a docker image built on this branch, with the master node-zwave-js branch, I get the following error and it doesn't come up:

```
2021-01-05 03:41:45.235 WARN STORE: scenes.json not found

Error: Cannot find module '/usr/src/app/node_modules/zwave-js/index.js'. Please verify that the package.json has a valid "main" entry

    at tryPackage (internal/modules/cjs/loader.js:295:19)

    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/usr/src/app/lib/ZwaveClient.js:11:5)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at require (/usr/src/app/node_modules/app-root-path/lib/app-root-path.js:14:11)

    at Object.<anonymous> (/usr/src/app/app.js:10:21)

    at Module._compile (internal/modules/cjs/loader.js:999:30) {

  code: 'MODULE_NOT_FOUND',

  path: '/usr/src/app/node_modules/zwave-js/package.json',

  requestPath: 'zwave-js'

}


```

**Comment by robertsLando** [comment]
@AlCalzone I think that error is caused by a wrong build of zwavejs? @blhoward2 could you tell me how you compiled the two repos?

**Comment by roflmao** [comment]
I have seen the Dockerfile.contrib building two versions of node-zwave-js and only the oldest from packages.json actually used. 
I saw it while trying to add a newer node-zwave-js master with devicesupport and got unknown device. 
I then found two config directories and one had the new device config while the other didnt.

**Comment by AlCalzone** [comment]
> 
> 
> @AlCalzone I think that error is caused by a wrong build of zwavejs? @blhoward2 could you tell me how you compiled the two repos?

Oh, yeah I changed that tonight trying to speed up CI tests.
You need to execute `yarn run build:full` now (or same with npm)

**Comment by blhoward2** [comment]
This now starts up, but the log files aren't populating still if they're supposed to do so. I see this on the console:

```
Logging to file:

/usr/src/app/store/zwavejs_37.log
```

But that file remains zero bytes. And no matter the logging level set the console is still logging INFO messages only.

**Comment by AlCalzone** [comment]
Need to use `zwave-js@6.0.0-alpha.3`. Logging is broken in alpha.2

**Comment by blhoward2** [comment]
How do I build that in?

**Comment by AlCalzone** [comment]
here: https://github.com/zwave-js/zwavejs2mqtt/pull/84/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R124

**Comment by blhoward2** [comment]
That’s what I built. Fix#23

**Comment by AlCalzone** [comment]
I meant you need to change that to `...alpha.3` and then `npm install` and build.

**Comment by AlCalzone** [comment]
Sorry, I was mistaken. alpha.2 should work

**Comment by blhoward2** [comment]
I am getting a console log, but only at the info level. And none in the file. I’ll try the newer version when my kids go to bed.

**Comment by AlCalzone** [comment]
Take your time, I'll need some sleep urgently

**Comment by blhoward2** [comment]
Somehow at one time I built an image off this branch that starts up, but it still does not startup if I clone both masters and then run:

DOCKER_BUILDKIT=1 docker build --build-arg SRC=git-clone-src --build-arg Z2M_BRANCH=fix#23 --build-arg ZWJ_BRANCH=master --no-cache -f zwavejs2mqtt/docker/Dockerfile.contrib -t zwavejs2mqtt .

I get the same error as above:

```
Error: Cannot find module '/usr/src/app/node_modules/zwave-js/index.js'. Please verify that the package.json has a valid "main" entry

    at tryPackage (internal/modules/cjs/loader.js:295:19)

    at Function.Module._findPath (internal/modules/cjs/loader.js:508:18)

    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)

    at Function.Module._load (internal/modules/cjs/loader.js:667:27)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at Object.<anonymous> (/usr/src/app/lib/ZwaveClient.js:11:5)

    at Module._compile (internal/modules/cjs/loader.js:999:30)

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

    at Module.load (internal/modules/cjs/loader.js:863:32)

    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

    at Module.require (internal/modules/cjs/loader.js:887:19)

    at require (internal/modules/cjs/helpers.js:74:18)

    at require (/usr/src/app/node_modules/app-root-path/lib/app-root-path.js:14:11)

    at Object.<anonymous> (/usr/src/app/app.js:10:21)

    at Module._compile (internal/modules/cjs/loader.js:999:30) {

  code: 'MODULE_NOT_FOUND',

  path: '/usr/src/app/node_modules/zwave-js/package.json',

  requestPath: 'zwave-js'

}
```

**Comment by robertsLando** [comment]
@blhoward2 I cannot reproduce your error on my PC, it's working

**Comment by robertsLando** [comment]
@roflmao @larstobi Seems the docker.contrib is still broken, @AlCalzone any clue? I think the changes you suggested for build are not enough

**Comment by larstobi** [comment]
looking at it

**Comment by roflmao** [comment]
git trolled me, git reset --hard && git pull and now it runs

**Comment by robertsLando** [comment]
@roflmao 
:man_shrugging:

**Comment by larstobi** [comment]
I just built it successfully on my machine :-) Also verified versions, an everything looks good to me.

**Comment by roflmao** [comment]
Extra quality assurance steps, thanks guys!

**Comment by robertsLando** [comment]
I think there are still some problems, I think in zwavejs log options. When restarting driver after a configuration update seems logging options are not respected

**Comment by blhoward2** [comment]
Confirmed that this now builds and starts with fix#23/master.

**Comment by AlCalzone** [comment]
Out of curiosity, what was missing/wrong?

**Comment by blhoward2** [comment]
I didn't change anything on my end if you're asking me.

**Comment by blhoward2** [comment]
I'd add that logging is still broken though. My log file isn't being populated.

```
Logging to file:

/usr/src/app/store/zwavejs_1.log
```

"logToFile":true,"logLevel":"silly","logEnabled":true}}

**Comment by blhoward2** [comment]
I know that you are all working on a bunch of things, but just a note that at this point the broken zwave logging is hampering testing other things. Like the cc/hail PR...I can't actually see any detail about the hails to get a good before picture because it doesn't respect the logging level of the console and isn't populating the log file. My network is still starting up now that I can build a docker off that branch (thanks!) but I'm unsure I'll actually be able to tell what is going on with the present logging.

**Comment by AlCalzone** [comment]
Logging has priority, since I can't really do anything with the issues that cannot post a log.

**Comment by aretakisv** [comment]
@robertsLando @blhoward2 @AlCalzone would it make sense to have issues created for individual issues, and keep a pull request clearly for Code reviewing?

we can always link issues to pull requests, this will keep clear the place

**Comment by blhoward2** [comment]
@aretakisv I debated that and am happy to do whatever is desired. Since this was an issue caused by this PR I ultimately decided to just post it here as it isn’t a bug in the master branch itself.

**Comment by AlCalzone** [comment]
Can't speak for @robertsLando but I am okay with discussing problems strictly related to a PR in the PR itself instead of hopping between issue and pr.

**Comment by AlCalzone** [comment]
`lib/Constants.js`, line 1 must be changed. `@zwave-js/config` no longer exports the methods `lookupMeterScale, lookupMeter`, instead they are now available through `driver.configManager`.

**Pull request merged**
