### PR TITLE
fix: issues with controller powerlevel settings

### LINKED ISSUE #2532: Issues with controller powerlevel settings
While doing a range test, I found some weird behavior for the powerlevel settings:

1. The values should be set together, not separate. I think this happens behind the scenes, but it should really not be necessary to send both changes separately:
    grafik

2. That's more for me: Z-Wave JS does an automatic refresh after setting the values. I think the API should be updated to reflect the verified values. Some sticks do not accept all settings and revert:
    powerlevel

3. Refreshing the values does not work. They get queried but never show up in the UI:
    powerlevel2

4. If you look closely at the log, refreshing the powerlevels also queries the region for some reason.

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2532

### CODE REVIEW

**Comment by robertsLando** [comment]
cc @AlCalzone

**Review by AlCalzone — CHANGES_REQUESTED** [review]
image
Reload button vanishes when the textboxes are empty.

---

Refreshing the powerlevel also refreshes the region (see log):
```
17:36:02.411 DRIVER » [REQ] [SerialAPISetup]
                        command: GetPowerlevel
                        payload: 0x08
17:36:02.415 SERIAL « [ACK]                                                                   (0x06)
17:36:02.417 SERIAL « 0x0106010b0863e971                                                   (8 bytes)
17:36:02.417 SERIAL » [ACK]                                                                   (0x06)
17:36:02.418 DRIVER « [RES] [SerialAPISetup]
                        command:               GetPowerlevel
                        normal powerlevel:     9.9 dBm
                        output power at 0 dBm: 23.3 dBm
17:36:02.426 SERIAL » 0x0104000b20d0                                                       (6 bytes)
17:36:02.426 DRIVER » [REQ] [SerialAPISetup]
                        command: GetRFRegion
                        payload: 0x20
17:36:02.433 SERIAL « [ACK]                                                                   (0x06)
17:36:02.435 SERIAL « 0x0105010b2000d0                                                     (7 bytes)
17:36:02.435 SERIAL » [ACK]                                                                   (0x06)
17:36:02.436 DRIVER « [RES] [SerialAPISetup]
                        command: GetRFRegion
                        region:  Europe
```

**Comment by robertsLando** [comment]
> Refreshing the powerlevel also refreshes the region (see log):

I know that, it uses a general method that updates all those properties, is that a problem?

**Comment by AlCalzone** [comment]
Seems unnecessary since both have the refresh button and I would expect that I have to refresh both separately, but it shouldn't matter.

**Pull request merged**
