### PR TITLE
fix: ensure settings contains default and do not throw errors

### LINKED ISSUE #2325: [Bug]: Nodes.json can be empty, when no configuration is set
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Snap

### Zwavejs2Mqtt version

6.5.2.c8e6d1a (snap rev 345)

### ZwaveJS version

Unknown

### Describe the bug

I've just started up ZwaveJs2MQTT on my raspberry pi using Snap, and I was testing out restarts to ensure that everything worked before configuring the app. I invoked `zwavejs2mqtt.restart` and then it didn't come back up.

```
# snap logs zwavejs2mqtt -n50
2022-03-19T14:12:47+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:47+01:00 zwavejs2mqtt.zwavejs2mqtt[59114]: Missing plug: «serial-port»
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.718 INFO APP: Version: 6.5.2.c8e6d1a
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.725 INFO APP: Application path:/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:  ______                       _     ___                  _   _
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: |___  /                      (_)   |__ \                | | | |
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:                             _/ |                      | |
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:                            |__/                       |_|
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: 2022-03-19 14:12:53.783 WARN STORE: scenes.json not found
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]: SyntaxError: /var/snap/zwavejs2mqtt/345/nodes.json: Unexpected end of JSON input
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at JSON.parse (<anonymous>)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at _readFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/node_modules/jsonfile/index.js:25:16)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at StorageHelper._getFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:51:20)
2022-03-19T14:12:53+01:00 zwavejs2mqtt.zwavejs2mqtt[59189]:     at StorageHelper.init (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:42:25)
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Failed with result 'exit-code'.
2022-03-19T14:12:53+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.336s CPU time.
2022-03-19T14:12:54+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Scheduled restart job, restart counter is at 2.
2022-03-19T14:12:54+01:00 systemd[1]: Stopped Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:54+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.336s CPU time.
2022-03-19T14:12:54+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:12:54+01:00 zwavejs2mqtt.zwavejs2mqtt[59238]: Missing plug: «serial-port»
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.214 INFO APP: Version: 6.5.2.c8e6d1a
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.221 INFO APP: Application path:/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:  ______                       _     ___                  _   _
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: |___  /                      (_)   |__ \                | | | |
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:    / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:   / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:  / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: /_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:                             _/ |                      | |
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:                            |__/                       |_|
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: 2022-03-19 14:13:00.279 WARN STORE: scenes.json not found
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]: SyntaxError: /var/snap/zwavejs2mqtt/345/nodes.json: Unexpected end of JSON input
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at JSON.parse (<anonymous>)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at _readFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/node_modules/jsonfile/index.js:25:16)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at StorageHelper._getFile (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:51:20)
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59314]:     at StorageHelper.init (/snap/zwavejs2mqtt/345/lib/node_modules/zwavejs2mqtt/server/lib/jsonStore.js:42:25)
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Main process exited, code=exited, status=1/FAILURE
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Failed with result 'exit-code'.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.355s CPU time.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Scheduled restart job, restart counter is at 3.
2022-03-19T14:13:00+01:00 systemd[1]: Stopped Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:13:00+01:00 systemd[1]: snap.zwavejs2mqtt.zwavejs2mqtt.service: Consumed 7.355s CPU time.
2022-03-19T14:13:00+01:00 systemd[1]: Started Service for snap application zwavejs2mqtt.zwavejs2mqtt.
2022-03-19T14:13:00+01:00 zwavejs2mqtt.zwavejs2mqtt[59361]: Missing plug: «serial-port»
```

If I poke at the file, `/var/snap/zwavejs2mqtt/345/nodes.json` its 0 bytes in size.

### To Reproduce

I don't think snap is related to the issue, but it should be something like this:

1. On a clean install, start up zwavejs2mqtt
2. The UI is accessible, if you do, the statistics prompt is shown. Clicking "Ok" will create "settings.json"
3. Do _not_ configure anything else
4. Invoke `zwavejs2mqtt.restart`, this restarts the app
5. Observe that the app does not start, the log shown is logged

### Expected behavior

It seems like there is a code path that can save `nodes.json`, but maybe fail since the zwave device is not configured?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2325

### CODE REVIEW

**Comment by robertsLando** [comment]
@kpine @LordMike could you give this  a try?

**Comment by LordMike** [comment]
I built the docker image, and ran it just once:

```
> docker run -it --rm test
/bin/sh: git: not found
2022-03-21 08:48:55.420 INFO APP: Version: 6.5.2
2022-03-21 08:48:55.421 INFO APP: Application path:/usr/src/app

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2022-03-21 08:48:55.429 WARN STORE: settings.json not found
2022-03-21 08:48:55.434 WARN STORE: scenes.json not found
2022-03-21 08:48:55.435 WARN STORE: nodes.json not found
2022-03-21 08:48:55.440 WARN STORE: users.json not found
2022-03-21 08:48:55.445 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
TypeError: Cannot read property 'disabled' of undefined
    at Gateway.start (/usr/src/app/server/lib/Gateway.js:180:29)
    at startGateway (/usr/src/app/server/app.js:235:14)
    at startServer (/usr/src/app/server/app.js:175:11)
```

**Comment by robertsLando** [comment]
@LordMike try now

**Comment by LordMike** [comment]
```
> docker run -it --rm test
/bin/sh: git: not found
2022-03-21 11:21:16.335 INFO APP: Version: 6.5.2
2022-03-21 11:21:16.337 INFO APP: Application path:/usr/src/app

 ______                       _     ___                  _   _
|___  /                      (_)   |__ \                | | | |
   / /_      ____ ___   _____ _ ___   ) |_ __ ___   __ _| |_| |_
  / /\ \ /\ / / _` \ \ / / _ \ / __| / /| '_ ` _ \ / _` | __| __|
 / /__\ V  V / (_| |\ V /  __/ \__ \/ /_| | | | | | (_| | |_| |_
/_____|\_/\_/ \__,_| \_/ \___| |___/____|_| |_| |_|\__, |\__|\__|
                            _/ |                      | |
                           |__/                       |_|

2022-03-21 11:21:16.347 WARN STORE: settings.json not found
2022-03-21 11:21:16.352 WARN STORE: scenes.json not found
2022-03-21 11:21:16.352 WARN STORE: nodes.json not found
2022-03-21 11:21:16.358 WARN STORE: users.json not found
2022-03-21 11:21:16.365 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
TypeError: Cannot read property 'on' of undefined
    at Gateway.start (/usr/src/app/server/lib/Gateway.js:174:24)
    at startGateway (/usr/src/app/server/app.js:235:14)
    at startServer (/usr/src/app/server/app.js:175:11)
```

**Comment by robertsLando** [comment]
Yeah stupid error, now I tried to run mine and it seems to work. LMK :)

**Comment by LordMike** [comment]
I can now run this PR with a volume, open the site, click ok to the tracking thing, close it down and start it up again without the dialog. So settings works, and all the other config files exist (no warnings) and can load.

There was _one_ error, which I can't reproduce:
```
2022-03-21 18:10:03.542 WARN STORE: settings.json not found
2022-03-21 18:10:03.547 WARN STORE: scenes.json not found
2022-03-21 18:10:03.563 INFO APP: Listening on port 8091 host 0.0.0.0 protocol HTTP
2022-03-21 18:10:03.582 WARN ZWAVE: Zwave driver not inited, no port configured
2022-03-21 18:10:07.032 INFO APP: GET / 200 9.743 ms - 1410
2022-03-21 18:10:07.125 INFO APP: GET /static/css/app.dfe48ed45f099bfc6154.css 200 5.229 ms - 644099
2022-03-21 18:10:07.136 INFO APP: GET /static/js/app.4530e1ff22bb0b44a365.js 200 4.160 ms - 2076062
2022-03-21 18:10:07.463 INFO APP: GET /api/auth-enabled 200 4.397 ms - 29
2022-03-21 18:10:07.722 INFO APP: GET /api/settings 200 89.283 ms - 12381
2022-03-21 18:10:07.724 INFO APP: GET /static/fonts/MaterialIcons-Regular.fa3334f.woff2 200 32.906 ms - 82492
2022-03-21 18:10:07.725 INFO APP: GET /static/logo.png 200 31.179 ms - 10014
2022-03-21 18:10:07.797 INFO APP: GET /static/favicons/favicon-32x32.png 200 1.477 ms - 1831
2022-03-21 18:10:07.801 INFO APP: GET /api/auth-enabled 304 2.011 ms - -
2022-03-21 18:10:07.803 INFO APP: GET /static/favicons/site.webmanifest 200 4.616 ms - 429
2022-03-21 18:10:09.035 ERROR APP: undefined
2022-03-21 18:10:09.036 INFO APP: POST /api/statistics 200 9.827 ms - 82
^C2022-03-21 18:10:17.421 WARN APP: Shutdown detected: closing clients...
2022-03-21 18:10:17.424 INFO GATEWAY: Closing Gateway...
2022-03-21 18:10:17.427 INFO ZWAVE: Client closed
```

I canceled the app (Cltr+c) shortly after this error..., so maybe it was shutting down when the error occurred.. 

In any case. I can't reproduce it right now (removing volume etc does nothing), so maybe it's just a fluke.

**Comment by robertsLando** [comment]
@LordMike Thanks for your report! I tried on my side and I cannot reproduce your error but I will keep it monitored.

**Comment by robertsLando** [comment]
@LordMike I may have fund what could go wrong here, it could happen that when you enable stats and driver is not ready it throws, now it silently fail with a warn log

**Pull request merged**
