### PR TITLE
feat: add `MQTT_NAME` env var

### PR DESCRIPTION
**Pull request by mannerydhe**
I added the option to configure the mqtt name using an env variable. 

I needed this in order to manage several pods in a kubernetes cluster.

### CODE REVIEW

**Comment by robertsLando** [comment]
@mannerydhe Could you add the env var to docs please? There is a doc dedicated to env vars :)

**Comment by mannerydhe** [comment]
> @mannerydhe Could you add the env var to docs please? There is a doc dedicated to env vars :)

Done!

**Review by robertsLando — APPROVED** [review]

**Comment by robertsLando** [comment]
Please rrun the command `npm run lint-fix`

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by AlCalzone** [comment]
@zwave-js-bot fix lint

**Review by robertsLando — APPROVED** [review]

**Pull request merged**
