### PR TITLE
[fix] HassDiscovery payload

### PR DESCRIPTION
**Pull request by billiaz**
- Convert to lower case
- Replace spaces with underscore

### CODE REVIEW

**Comment by billiaz** [comment]
fixes issues 
https://github.com/zwave-js/zwavejs2mqtt/issues/94
https://github.com/zwave-js/zwavejs2mqtt/issues/91
https://github.com/zwave-js/zwavejs2mqtt/issues/60

**Comment by robertsLando** [comment]
@billiaz I would instead fix the object id. Let me show you

**Comment by billiaz** [comment]
> @billiaz I would instead fix the object id. Let me show you

Thinking of it.
If we check object_id after is defined and change it, should work right? for instance 

To be clear:
1. create a function which converts any string passed to lowercase and replace spaces with underscores.
2. Update object_id earlier in code, where object_id is defined, using the function
3. have a function for other uses too (the 1 point)

@robertsLando something like that?

**Comment by robertsLando** [comment]
@billiaz FIxed in #99 . Thanks for pointing out the origin of the fix :smile:

**Pull request closed without merging**
