### PR TITLE
build: docker build optimization (split stages)

### PR DESCRIPTION
**Pull request by ahochsteger**
This PR tries to optimize the long docker build times (~30min) on GitHub to speed up the development process.

The approach taken here is to move the time-consuming `npm install` steps into base images that can be reused by subsequent builds if dependencies did not change (which is the case most of the time).

**Created images (WIP):**

* `zwavejs/zwavejs2mqtt-builder-base`
* `zwavejs/zwavejs2mqtt-builder`
* `zwavejs/zwavejs2mqtt-runtime-base`
* `zwavejs/zwavejs2mqtt-runtime`

**Building locally:**

The following `docker-compose` files are provided to simplify building and testing this PR locally:
* `docker-compose.build.yml`: Build images
* `docker-compose.runtime.yml`: Run images for testing

Example usages:

```bash
# Full rebuild (e.g. if package.json changed):
docker-compose -f docker/docker-compose.build.yml build

# Fast build (e.g. if package.json did not change since last full build):
docker-compose -f docker/docker-compose.build.yml build zwavejs2mqtt-builder zwavejs2mqtt-runtime
```

**Github actions:**

The GitHub actions don't use `docker-compose` for building to keep the required multi-platform support.
Caching (using `actions/cache@v2`) has been integrated as introduced in PR #549.

**Local build time improvements:**

The build times are measured on my local notebook (i5-6440HQ CPU @ 2.60GHz with SSDs):

* Original build (no cache, nodejs image pulled): **2m58s**
* Full new 4-image multi-stage build (no cache, nodejs image pulled): **3m52s (140% of original)**
* Fast multi-stage build without dependency changes: **1m31s (50% of original)**

Some more statistics to see if the increased build time for full builds are worth it:
* Number of total commits on the master branch: **1013**
* Number of commits with changes in package.json: **237 (23% of total)**
* Cumulative build time of original build system: 1013*178s=180314s => **50h**
Cumulative build time (new build): 237*232s + (1013-237)*91s=125600  => **35h (70% of original)**

**Next steps:**

- [x] Integrate into GitHub actions
- [ ] Solve base image caching. Evaluate possible solutions:
  - `actions/cache@v2`
  - `satackey/action-docker-layer-caching@v0.0.11`
  - `whoan/docker-build-with-cache-action@v5`
- [ ] Get feedback on the taken approach
- [ ] Optimize arch-independend builds and re-use results for arch-dependent images
- [ ] Cleanup (see TODOs in code)

**Related:**

* #549
* <https://github.community/t/is-it-possible-to-run-the-job-only-when-a-specific-file-changes/115484/2>

### CODE REVIEW

**Comment by ahochsteger** [comment]
@robertsLando, @chrisns may you have a look at this approach?
The GitHub build does not yet work, but it's working locally using `docker-compose` (see description).

**Comment by robertsLando** [comment]
I feel like this would make the build process too much complex (with low benefits) . Thoughts @chrisns ?

**Comment by chrisns** [comment]
Will look at it tomorrow

**Comment by robertsLando** [comment]
@ahochsteger Looking at your changes, this looks good only while deps don't change too much, the problem is that I get deps updates every day (almost). 

IMO this is not the best approach to use. I have an idea btw for anmother one

**Comment by robertsLando** [comment]
Fixed by https://github.com/zwave-js/zwavejs2mqtt/pull/740

**Pull request closed without merging**
