### PR TITLE
fix: better sanitize topics

### PR DESCRIPTION
**Pull request by robertsLando**
Related to #920 

cc @blhoward2 @tmaroschik let me know your feedback on this please

### CODE REVIEW

**Review by tmaroschik — APPROVED** [review]
This change looks fine.

One thing that might cause problems down the road is, that `utils.sanitizeTopic()` doesn't remove special chars like umlauts or emojis. So instead of just removing "known" invalid chars, it would be better to remove all "unknown" invalid chars with a regex like `str.replace(/[^A-Za-z0-9-_]/g, "")` or even transliterate in advance to that if you want to go the extra mile.

The topic char constraints apparently aren't defined by the protocol spec itself (they basically allow every UTF-8 char, except slash/star/etc.), but rather by the clients and their capabilities (UTF-8 on an ESP consumes more memory than plain ASCII).

**Comment by robertsLando** [comment]
> So instead of just removing "known" invalid chars, it would be better to remove all "unknown" invalid chars with a regex like str.replace(/[^A-Za-z0-9-_]/g, "") or even transliterate in advance to that if you want to go the extra mile.

You right, I think a regex like `/[^A-Za-z0-9-_]/g` should do the job!

**Comment by robertsLando** [comment]
@tmaroschik I have also added the `/` char to allowed chars in the regex as it should not be removed by default.

**Review by tmaroschik — APPROVED** [review]
True. Looks good.

**Comment by robertsLando** [comment]
Wait wait... by default nodeName alreadt contains location-name value, if `ignoreLocation` setting is false. What we should do so is to just sanitize nodename

**Pull request merged**
