### PR TITLE
fix: unknown manufacturer

### LINKED ISSUE #347: [bug] Unknown manufacturer/product even though zwave-js eventually detects it
### Version

Build/Run method: Docker

zwavejs2mqtt version: 1.0.0-rc.1 (master branch)
zwavejs version: 6.0.2

### Describe the bug

(For updated logs and similar problems with nodes 25+36 see: [https://github.com/zwave-js/zwavejs2mqtt/issues/347#issuecomment-767346459])

I still have the problem with "Unknown manufacturer / product" for some battery-powered devices that take a longer time to be interviewed successfully, esp. if they are a bit further from the Z-Wave controller away.
Most of the time it is possible to trigger a re-interview in zwavejs2mqtt and waking up the device which causes the device to fully show up in the nodes table.
Unfortunately some devices show then up as "Unknown manufacturer/product" which cannot be changed to the correct names by re-interviewing again, even though zwave-js is able to successfully detect the name - although it may take a longer time (e.g. 20-30h).
Here are screenshots for the 2 problematic nodes (25, 150):
image
image

The attached logs for both zwavejs2mqtt and zwave-js show about 30 hours from a fresh start (empty store directory) up until after the problem occurred again and include all the relevant config files: [files.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5869673/files.zip)
The problematic nodes are: 25 and 150 - both Shenzhen Neo NAS-DS01Z Door/Window sensors.

These are some interesting log lines from zwavejs2mqtt:
```
2021-01-24 18:08:31.896 INFO ZWAVE: Node 150 ready: Shenzhen Neo Electronics Co., Ltd. - NAS-DS01Z (Door/Window Sensor)
2021-01-25 07:31:16.974 INFO ZWAVE: Node 150 ready: Shenzhen Neo Electronics Co., Ltd. - NAS-DS01Z (Door/Window Sensor)
2021-01-25 18:18:01.868 INFO ZWAVE: Node 150 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-25 19:09:13.604 INFO ZWAVE: Node 25: value added 25-134-0-protocolVersion => undefined
2021-01-25 19:09:13.607 INFO ZWAVE: Node 25: value added 25-134-0-firmwareVersions => undefined
2021-01-25 19:09:13.609 INFO ZWAVE: Node 25: value added 25-114-0-manufacturerId => undefined
2021-01-25 19:09:13.612 INFO ZWAVE: Node 25: value added 25-114-0-productType => undefined
2021-01-25 19:09:13.615 INFO ZWAVE: Node 25: value added 25-114-0-productId => undefined
2021-01-25 19:09:13.617 INFO ZWAVE: Node 25: value added 25-128-0-level => undefined
2021-01-25 19:09:13.620 INFO ZWAVE: Node 25: value added 25-128-0-isLow => undefined
2021-01-25 19:09:13.623 INFO ZWAVE: Node 25: value added 25-132-0-wakeUpInterval => 43200
2021-01-25 19:09:13.626 INFO ZWAVE: Node 25: value added 25-132-0-controllerNodeId => undefined
2021-01-25 19:09:13.652 INFO ZWAVE: Node 25 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-25 19:09:13.653 INFO ZWAVE: Node 25: interview completed, all values are updated
2021-01-25 20:32:50.297 INFO ZWAVE: Node 150 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-25 20:33:43.034 INFO ZWAVE: Node 150 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-25 20:34:47.740 ERROR ZWAVE: Interview of node 150 has failed: Attempt 1/5 failed
2021-01-25 21:20:29.828 INFO ZWAVE: Node 150 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-25 21:48:26.261 INFO ZWAVE: Node 25 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
```
Interesting is, that it seems that zwavejs2mqtt already got the correct manufacturer and product names but I don't remember to have seen them in the UI - otherwise I wouldn't have triggert a re-interview that often. One day later the device is not shown empty in the UI anymore but shows up as "Unknown manufacturer/device".

These are interesting log lines from zwave-js (from date 2021-01-25 - btw. can we output the date in the zwave-js logs too?) where a re-interview of node 150 has been triggered:
```
18:08:27.863 CNTRLR « [Node 150] received response for manufacturer information:
                        manufacturer: Shenzhen Neo Electronics Co., Ltd. (0x0258)
                        product type: 0x03
                        product id:   0x1082
18:08:27.863 CNTRLR   [Node 150] [+] [Manufacturer Specific] interviewComple [Endpoint 0] [internal]
                      te: true
...
19:07:37.194 CNTRLR « [Node 025] received response for manufacturer information:
                        manufacturer: Shenzhen Neo Electronics Co., Ltd. (0x0258)
                        product type: 0x03
                        product id:   0x1082
19:07:37.195 CNTRLR   [Node 025] [+] [Manufacturer Specific] interviewComple [Endpoint 0] [internal]
                      te: true
...
19:07:38.796 CNTRLR « [Node 025] received response for manufacturer information:
...
20:32:35.216 CNTRLR « [Node 150] received response for manufacturer information:
...
20:32:35.480 CNTRLR « [Node 150] received response for manufacturer information:
...
20:33:34.234 CNTRLR « [Node 150] received response for manufacturer information:
...
21:20:25.652 CNTRLR « [Node 150] received response for manufacturer information:
```
A related question:
What happens, if a device reports data (e.g. door opened/closed) while it has not yet been successfully interviewed?
I have the suspicion that this may trigger a race condition, but I have not been able to track this down.
Hopefully the logs and config files give enough information to find out what's going on.

### To Reproduce

1. Make sure there are no files in the store directory
2. Start zwavejs2mqtt
3. Wait hours until there are empty devices left, that could not yet interviewed
4. Trigger a re-interview of the remaining ones and waking them up (e.g. press button 3x on Door/Window sensor)
5. Wait a few minutes
6. Repeat for devices that could not be interviewed correctly
7. Eventually some devices end up as being detected as "Unknown manufacturer/product" which are stuck in the ProtocolInfo stage

### Expected behavior

zwavejs2mqtt should be able to recover from an "Unknown" device state as soon as zwave-js is able to correctly detect the device.

### Additional context

This issue has already been reported as part of #233 where fixes have been committed which did not reproduce the problem until now why I'm opening a new issue with new information.

### LINKED ISSUE #373: [bug] ready: Unknown manufacturer undefined; log shows manufacturer id
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: 1.0.0-rc.1+423a7e7.423a7e7
zwavejs version: 6.1.0-5d49c45

### Describe the bug
I have an Aeotec Door/Window sensor 7 which Z2M cannot identify the manufacturer of. I have other devices of the same kind, and they don't exhibit this issue. 

In the log below, I've reinterviewed the node (24), and right at the start, we can see that the Manufacturer (881) is identified (zwave-js confirms this).. But at the end of the process, z2m logs `Node 24 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)`. I'm not sure why the information was lost.

I will preemptively say that this particular device has an extremely bad battery.. 

### To Reproduce
N/A

### Expected behavior
Node manufacturer / type is identified.

### Additional context
```
2021-01-27 18:09:43.498 INFO APP: Zwave api call: refreshInfo [ 24, [length]: 1 ]
2021-01-27 18:09:43.524 INFO ZWAVE: Success zwave api call refreshInfo
2021-01-27 18:09:43.527 INFO ZWAVE: Node 24 is now awake
2021-01-27 18:09:43.966 INFO ZWAVE: Node 24: value added: 114-0-manufacturerId => 881
2021-01-27 18:09:43.967 INFO ZWAVE: Node 24: value added: 114-0-productType => 2
2021-01-27 18:09:43.967 INFO ZWAVE: Node 24: value added: 114-0-productId => 7
2021-01-27 18:09:44.203 INFO ZWAVE: Node 24: value added: 134-0-libraryType => 3
2021-01-27 18:09:44.204 INFO ZWAVE: Node 24: value added: 134-0-protocolVersion => 6.7
2021-01-27 18:09:44.205 INFO ZWAVE: Node 24: value added: 134-0-firmwareVersions => 1.1
2021-01-27 18:09:47.175 INFO ZWAVE: Node 24: value added: 134-0-sdkVersion => 6.81.1
2021-01-27 18:09:47.177 INFO ZWAVE: Node 24: value added: 134-0-applicationFrameworkAPIVersion => 4.1.1
2021-01-27 18:09:47.178 INFO ZWAVE: Node 24: value added: 134-0-applicationFrameworkBuildNumber => 52445
2021-01-27 18:09:47.179 INFO ZWAVE: Node 24: value added: 134-0-hostInterfaceVersion => unused
2021-01-27 18:09:47.179 INFO ZWAVE: Node 24: value added: 134-0-hostInterfaceBuildNumber => 0
2021-01-27 18:09:47.180 INFO ZWAVE: Node 24: value added: 134-0-zWaveProtocolVersion => 6.7.0
2021-01-27 18:09:47.181 INFO ZWAVE: Node 24: value added: 134-0-zWaveProtocolBuildNumber => 97
2021-01-27 18:09:47.182 INFO ZWAVE: Node 24: value added: 134-0-applicationVersion => 1.1.0
2021-01-27 18:09:47.183 INFO ZWAVE: Node 24: value added: 134-0-applicationBuildNumber => 0
2021-01-27 18:09:47.390 INFO ZWAVE: Node 24: metadata updated: 132-0-wakeUpInterval
2021-01-27 18:09:47.596 INFO ZWAVE: Node 24: value added: 132-0-wakeUpInterval => 86400
2021-01-27 18:09:47.598 INFO ZWAVE: Node 24: value added: 132-0-controllerNodeId => 1
2021-01-27 18:09:48.014 INFO ZWAVE: Node 24: value added: 128-0-level => 86
2021-01-27 18:09:48.015 INFO ZWAVE: Node 24: value added: 128-0-isLow => false
2021-01-27 18:09:48.019 INFO ZWAVE: Node 24: metadata updated: 112-0-1
2021-01-27 18:09:48.019 INFO ZWAVE: Node 24: metadata updated: 112-0-2
2021-01-27 18:09:48.020 INFO ZWAVE: Node 24: metadata updated: 112-0-3
2021-01-27 18:09:48.021 INFO ZWAVE: Node 24: metadata updated: 112-0-4
2021-01-27 18:09:48.021 INFO ZWAVE: Node 24: metadata updated: 112-0-5
2021-01-27 18:09:48.022 INFO ZWAVE: Node 24: metadata updated: 112-0-6
2021-01-27 18:09:48.022 INFO ZWAVE: Node 24: metadata updated: 112-0-7
2021-01-27 18:09:48.022 INFO ZWAVE: Node 24: metadata updated: 112-0-8
2021-01-27 18:09:48.023 INFO ZWAVE: Node 24: metadata updated: 112-0-9
2021-01-27 18:09:48.023 INFO ZWAVE: Node 24: metadata updated: 112-0-10
2021-01-27 18:09:48.023 INFO ZWAVE: Node 24: metadata updated: 112-0-11
2021-01-27 18:09:48.024 INFO ZWAVE: Node 24: metadata updated: 112-0-12
2021-01-27 18:09:48.024 INFO ZWAVE: Node 24: metadata updated: 112-0-13
2021-01-27 18:09:48.024 INFO ZWAVE: Node 24: metadata updated: 112-0-14
2021-01-27 18:09:48.025 INFO ZWAVE: Node 24: metadata updated: 112-0-15
2021-01-27 18:09:48.193 INFO ZWAVE: Node 24: value added: 112-0-1 => 0
2021-01-27 18:09:48.395 INFO ZWAVE: Node 24: value added: 112-0-2 => 0
2021-01-27 18:09:48.605 INFO ZWAVE: Node 24: value added: 112-0-3 => 7
2021-01-27 18:09:48.815 INFO ZWAVE: Node 24: value added: 112-0-4 => 0
2021-01-27 18:09:49.024 INFO ZWAVE: Node 24: value added: 112-0-5 => 0
2021-01-27 18:09:49.235 INFO ZWAVE: Node 24: value added: 112-0-6 => 2
2021-01-27 18:09:49.452 INFO ZWAVE: Node 24: value added: 112-0-7 => 255
2021-01-27 18:09:49.665 INFO ZWAVE: Node 24: value added: 112-0-8 => 0
2021-01-27 18:09:49.875 INFO ZWAVE: Node 24: value added: 112-0-9 => 0
2021-01-27 18:09:50.084 INFO ZWAVE: Node 24: value added: 112-0-10 => 0
2021-01-27 18:09:50.302 INFO ZWAVE: Node 24: value added: 112-0-11 => 3
2021-01-27 18:09:50.505 INFO ZWAVE: Node 24: value added: 112-0-12 => 1
2021-01-27 18:09:50.715 INFO ZWAVE: Node 24: value added: 112-0-13 => 0
2021-01-27 18:09:50.924 INFO ZWAVE: Node 24: value added: 112-0-14 => 0
2021-01-27 18:09:51.134 INFO ZWAVE: Node 24: value added: 112-0-15 => 50
2021-01-27 18:09:55.267 INFO ZWAVE: Node 24: metadata updated: 91-0-scene-001
2021-01-27 18:09:55.690 INFO ZWAVE: Node 24: metadata updated: 113-0-Access Control-Door state
2021-01-27 18:09:55.889 INFO ZWAVE: Node 24: metadata updated: 113-0-Home Security-Cover status
2021-01-27 18:09:56.101 INFO ZWAVE: Node 24: value added: 113-0-Home Security-Cover status => 0
2021-01-27 18:09:56.131 INFO ZWAVE: Node 24 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-27 18:09:56.132 INFO ZWAVE: Node 24: interview completed, all values are updated
2021-01-27 18:09:57.198 INFO ZWAVE: Node 24 is now asleep
```

I've dumped the node, after the interview above: [node_24.json.txt](https://github.com/zwave-js/zwavejs2mqtt/files/5882204/node_24.json.txt).

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #373
Fixes #347

### CODE REVIEW

**Comment by AlCalzone** [comment]
Like we discussed, I would do it differently. When node is ready, use `getDefinedValueIDs()` to
1. detect which values are added and add them
2. detect which values were removed and remove them
3. update the others.

**Comment by robertsLando** [comment]
> Like we discussed, I would do it differently. When node is ready, use getDefinedValueIDs() to

Isn't the result of what I did the same?

**Comment by AlCalzone** [comment]
The way I'm seeing it, you do 2. but not 1. or 3.

**Comment by robertsLando** [comment]
@AlCalzone When node is ready I get a reference of the existing node values, _clear all actual node values_ , I get all the new defined values, I parse one by one and I check if it was existing (and if it has changed). The removed ones are not there so and the new ones are reported

**Comment by AlCalzone** [comment]
Ok then I didn't understand the consequences.

**Pull request merged**
