### PR TITLE
docs: removing entities from HASS

### PR DESCRIPTION
**Pull request by LordMike**
See #254

Needs:

* [ ] Check if steps for re-discovery (push discovery doc) is correct.

### CODE REVIEW

**Comment by robertsLando** [comment]
@LordMike Let me know when this is ready, will be useful!

**Comment by LordMike** [comment]
Actually. Since disabling the HASS integration on my end, I can't see that part of the UI anymore.. Can you confirm if the steps for rediscovery are correct?

**Comment by LordMike** [comment]
Also. With github actions, it's possible to run some CI stuff only if certain paths are affected. So for these PR's, you could avoid rebuilding the application and running linters etc.. 

This could be done by adding path arguments to all jobs, where docs stuff only  runs when `docs/**` is affected, and the source stuff only runs when `src/**` (or whatever) is affected.

[Docs](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths).

**Comment by robertsLando** [comment]
@LordMike Thanks for the suggestion about the ignore path, didn't know about that! 

Anyway the steps are a little different, you should press on `Rediscover Node` button and now node details are shown in the expanded row of the table

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by LordMike** [comment]
I've changed it to `Rediscover Node`:

> Note that in order for a removed entity to appear again, it must be published by **zwavejs2mqtt** again. This happens automatically for new devices, if enabled, alternatively it can be done manually by selecting the node in **zwavejs2mqtt**, and then for each HASS device clicking `Rediscover Node`.

**Pull request merged**
