### PR TITLE
fix(hass): inovelli lzw42 multi color bulb discovery update

### PR DESCRIPTION
**Pull request by DanielWinks**
Updated discovery to use changes found in [ZwaveJS #1782](https://github.com/zwave-js/node-zwave-js/pull/1782)

Fully working and tested on my box™

### CODE REVIEW

**Comment by DanielWinks** [comment]
@zwave-js-bot fix lint

**Comment by DanielWinks** [comment]
@zwave-js-bot fix lint

**Review by robertsLando — DISMISSED** [review]

**Comment by robertsLando** [comment]
@DanielWinks Could you fix lints on your branch? The bot is disabled atm as we found a problem with it.

Just run the command `npm run lint-fix`

**Review by robertsLando — APPROVED** [review]
LGTM

**Pull request merged**
