### PR TITLE
fix: manually add missing values on updates

### LINKED ISSUE #1044: [bug] Basic set events not sent to mqtt anymore?
### Version

**Checklist:**

- [X ] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X ] I have checked the troubleshooting section and my problem is **not** described there.
- [ X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [x ] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt: 3.2.0
zwave-js: 7.1.1

### Describe the bug

Until some unknown period in the past, basic set events from devices with a compat flag to undo the mapping and treat them as an event appeared under command class 32 under 32/0/event. After a complete rebuild of my network I no longer see 32 under any devices regardless of whether I use:

1. ValueID Topics
2. Named Topics (for this one basic isn't listed)

Double tapping my GE switches does send through the event properly (I can see it in HA) and I see it in the zwavejs1mqtt log. But I don't see any messages anywhere in mqtt.

With named topics:
Screen Shot 2021-04-12 at 12 18 13 AM

With ValueID topics:

Screen Shot 2021-04-12 at 12 42 51 AM

### Expected behavior

Double tap up/down should generate an event notification with a value of 255/0, and this should appear in mqtt.

### Additional context

zwave-js:
```
2021-04-12T04:38:31.385Z CNTRLR   [Node 002] treating BasicCC::Set as a value event
2021-04-12T04:38:31.385Z CNTRLR   [Node 002] [!] [Basic] event: 255                                 [Endpoint 0]
```

zwavejs2mqtt:

[node2.log](https://github.com/zwave-js/zwavejs2mqtt/files/6293936/node2.log)

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #1044

### CODE REVIEW

**Comment by towerhand** [comment]
Sure, are you planning to merge to master? or should I build it on my pi3?

**Comment by robertsLando** [comment]
@towerhand If you are able to build it, do it. I merged it to master because users struggle with custom builds, but I prefer to have this fixed before merging

**Comment by towerhand** [comment]
Ok, building now. Should be 15-20 min to report back.

**Comment by towerhand** [comment]
Bingo, I think you got it.

Just adding the logs, just in case you would like to check them.

[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6304412/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment]
```
2021-04-13 09:22:42.177 DEBUG MQTT: Publishing to zwave2jsmqtt/master_bedroom_fan/32/0/event: {
  time: 1618323762175,
  value: 0,
  nodeName: 'master_bedroom_fan',
  nodeLocation: ''
} with options { qos: 1, retain: true }
2021-04-13 09:22:42.180 DEBUG MQTT: Publishing to zwave2jsmqtt/master_bedroom_fan/32/0/event: {
  time: 1618323762179,
  value: 0,
  nodeName: 'master_bedroom_fan',
  nodeLocation: ''
} with options { qos: 1, retain: false }
```

Works but needs a fix. Need to dedupe this and fix the retain on the first one

**Comment by towerhand** [comment]
I'll be around if you need further testing. Thanks for looking into it and fixing it.

**Comment by robertsLando** [comment]
@towerhand Just submitted a fix to dedupe updates and correctly set the stateless flag. Could you test this again please and send me the logs?

Thanks to you for helping with testing 💪🏼

**Comment by towerhand** [comment]
Ok, I'm assuming I have to use the same `fix-notifications` brach for the custom build, I'll report back right after it gets done building.

**Comment by robertsLando** [comment]
yeah this is the branch, I have pushed a change to fix both the dedupe and the retain problem

**Comment by towerhand** [comment]
pi locked up, gotta build it again.

**Comment by robertsLando** [comment]
Still having problems? If so don't warry I can merge this anyway

**Comment by towerhand** [comment]
Finally built.
[zwavejs2mqtt-store.zip](https://github.com/zwave-js/zwavejs2mqtt/files/6305189/zwavejs2mqtt-store.zip)

**Comment by robertsLando** [comment]
No worries thanks! Based on your logs it's working perfectly 🎉 Available on version 3.3.0

**Comment by towerhand** [comment]
Hello @robertsLando, this fix is working great, only problem I have found is that zjs2m is sending the notification event with a retained flag when it's not supposed to. Would you like me to create a new issue?

**Pull request merged**
