### PR TITLE
feat(ui): visualize running firmware updates

### LINKED ISSUE #2110: [feat] Visualize running firmware updates
**Is your feature request related to a problem? Please describe.**
See #2093

Visualize a progress bar for OTA updates, so the progress is visible to users.

**Describe the solution you'd like**
@robertsLando hinted to making a new column on the devices list for this, but I suggest reusing the "fw" column -- it will only contain additional data when an update is running.

I've tried to prototype it with HTML editing in the picture below. (I know that a more fancy progress bar exists, so please use that :P)

image

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2110

Schermata da 2021-12-29 16-41-05

### CODE REVIEW

**Comment by robertsLando** [comment]
@LordMike Cannot test this my own, could you give this a try?

**Comment by LordMike** [comment]
Can you build an image for it?

I've recently formatted and my docker setup is broken :/

... I could take this opportunity and actually fix it ... :P

**Comment by robertsLando** [comment]
> Can you build an image for it?

I could merge this to master and then you can use `master` tag, I tried it my self by emulating an update via code and it seems working so shouldn't create any problem

**Comment by LordMike** [comment]
I'll run a `:dev` later to test it out then .. :)

**Comment by robertsLando** [comment]
@LordMike `dev` doesn't exists anymore, it has been replaced by `master` tag

**Pull request merged**
