### PR TITLE
chore(docker): docker labels opencontainers v2

### PR DESCRIPTION
**Pull request by chrisns**
alternative for #257 to #262

### CODE REVIEW

**Comment by robertsLando** [comment]
@chrisns What about adding the git hash, build date and other labels? Should we calculate them in a previous step and put them in outputs?

**Comment by chrisns** [comment]
The plug-in does those automatically

**Comment by robertsLando** [comment]
Also with that I could remove the label mantainer inside the dockerfile right?

**Comment by chrisns** [comment]
See the build log output

**Comment by chrisns** [comment]
> Also with that I could remove the label mantainer inside the dockerfile right?

Yes, sorry forgot to tidy that up

**Comment by robertsLando** [comment]
@chrisns Check my latest changes

**Pull request merged**
