### PR TITLE
chore(docker): add zwave-js server port binding in docker-compose.yml

### PR DESCRIPTION
**Pull request by scyto**
added port expose for new zwave-js websocket server and annotations to help the new.

### CODE REVIEW

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
@zwave-js-bot lint fix

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Comment by robertsLando** [comment]
@zwave-js-bot rename commit

**Comment by robertsLando** [comment]
@zwave-js-bot fix lint

**Review by robertsLando — APPROVED** [review]

**Comment by gottsman** [comment]
Is there a related patch? I don't see the container running anything on port 3000 internally with netstat.

**Comment by robertsLando** [comment]
> Is there a related patch? I don't see the container running anything on port 3000 internally with netstat.

Have you enabled zwavejs-server from settings?

**Comment by gottsman** [comment]
If an issue is better, I can create one...

Image: zwavejs/zwavejs2mqtt:latest

I am not able to find the option to enable... When I view the screenshots, I don't see a zwave-js version within the control panel nor the "store" and "store explorer"

https://zwave-js.github.io/zwavejs2mqtt/#/screenshots

**Comment by robertsLando** [comment]
In zwave section you will see a flag to enable it:

Schermata da 2021-01-26 16-34-45

**Comment by gottsman** [comment]
Here is what I see...

image

**Comment by robertsLando** [comment]
@gottsman I think you have an outdated version. Try to pull the `dev` tag

**Comment by gottsman** [comment]
Bingo! It works with the dev image.

**Pull request merged**
