### PR TITLE
fix: force allowed apis to be a valid method of ZwaveClient

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Review by AlCalzone — APPROVED** [review]
LGMT, just keep in mind that this "force" only applies to the types, JS and the frontend can still do whatever it wants unless it respects your types.

**Comment by robertsLando** [comment]
@AlCalzone Not working yet, this is the implementation of your suggestion but seems that isn't validating the props correctly

**Comment by AlCalzone** [comment]
Let me check

**Comment by AlCalzone** [comment]
Can you try my commit? Seems that the `any` in `extends (EventEmitter as any)` wasn't good for this kind of stuff.

**Comment by robertsLando** [comment]
```
TSError: ⨯ Unable to compile TypeScript:
Error: lib/Gateway.ts(1950,31): error TS2344: Type 'string | boolean | (<TEvent extends keyof ZwaveClientEventCallbacks>(event: TEvent, callback: ZwaveClientEventCallbacks[TEvent]) => ZwaveClient) | ... 61 more ... | (<TEvent extends keyof ZwaveClientEventCallbacks>(event: TEvent, ...args: Parameters<...>) => boolean)' does not satisfy the constraint '(...args: any) => any'.
  Type 'string' is not assignable to type '(...args: any) => any'.
```

**Comment by robertsLando** [comment]
Seems that you impoorted `applyMixin` from `lib/utils` but there is no implementation of such method in utils

**Comment by robertsLando** [comment]
Ok I have added it but seems that `keyof` opperator doens't 'fetch' private methods from class, any suggestion?

**Comment by AlCalzone** [comment]
> Seems that you impoorted applyMixin from lib/utils but there is no implementation of such method in utils

Weird... It was there when I tested. Here you go: https://github.com/zwave-js/node-zwave-js/blob/4d9d317edf5192bec654d229fb8bc86c1966df29/packages/shared/src/inheritance.ts#L12-L41

> `keyof` opperator doens't 'fetch' private methods from class, any suggestion?

Its not supposed to.

**Comment by robertsLando** [comment]
@AlCalzone I have found a 'compressed' solution for the `applyMixin`:

```ts
export function applyMixin(derivedCtor: any, constructor: any) {
	Object.getOwnPropertyNames(constructor.prototype).forEach((name) => {
		Object.defineProperty(
			derivedCtor.prototype,
			name,
			Object.getOwnPropertyDescriptor(constructor.prototype, name) ||
				Object.create(null)
		)
	})
}
```

**Comment by AlCalzone** [comment]
Two problems with that.
1.) `any` should really be replaced with a constructor type
2.) This only works for "shallow" mixins. when a mixin inherits from another class, this will break.

**Comment by robertsLando** [comment]
Ok I have added yours

**Pull request merged**
