### PR TITLE
fix: better node initialization

### LINKED ISSUE #217: [bug] Node rename is not always respected in MQTT
Official container `zwavejs/zwavejs2mqtt:1.0.0-alpha.2`. 
Mosquitto 2.0.4.
Gateway is set for ValueID topics with enforced using of node names. 
Devices are created without names. Now, when I add a name for them, it is saved in ZWave, all good. 
For some devices (smart plugs) the topics in MQTT get updated, and once I reload HomeAssistant (after killing the devices there), I get pretty names for devices and entities. 
Unfortunately, for Fibaro buttons (FGPB101) they stay as `nodeXX`, no matter what. Tried removing and healing in several ways. The name in ZWave is updated, MQTT topics are always numbered.

Please advise me what information to provide to help understand the trouble.

### LINKED ISSUE #256: After restarting, most of the devices show Unknown manufacturer undefined [bug]
**Version**
latest docker dev build 1.0.0-beta.0
Build/Run method
- [x] Docker
- [ ] PKG
- [ ] Manually built (git clone - npm install - npm run build ) 

zwavejs2mqtt version: latest docker dev build 1.0.0-beta.0

**Describe the bug**
Hi,
I had everything configured perfectly. All nodes were appearing with the correct manufacturer and product in the device list.
After a restart, I can see almost all nodes as Unknown manufacturer undefined. Tried to restart few times.
I was expected to see them all with the manufacturers that were before the restart.
Some of the devices show empty lines in the device list.
I have 40 zwave devices.
I hope I have enough information here, if something is missing, please let me know.

**Expected behavior**
All the devices should have loaded from the cache with their information.
Is this correct? is this get saved somewhere?

Screen Shot 2021-01-16 at 9 05 33

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #217
Fixes #256

### CODE REVIEW

**Comment by robertsLando** [comment]
@ahochsteger could you give this a try?

**Comment by ahochsteger** [comment]
@robertsLando I just tried out this branch with your changes.

Unfortunately it happened again that a battery-powered device (Fibaro Button) results in an "Unknown manufacturer" / "Unknown product", even though zwave-js was able to detect the manufacturer after a "Refresh info":
image

Here are the full logs:
[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826600/zwavejs2mqtt.log)
[zwavejs_63428.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826601/zwavejs_63428.log)

I suspect that the problem lies in the fact that if a battery-powered device cannot be fully initialized, zwave-js will eventually set the node to ready without knowing the manufacturer and product.
When a full "Refresh info" is done at some time later zwave-js correctly updates the missing manufacturer / product data and even zwavejs2mqtt recognizes them but it seems that manufacturer and product are not updated in the UI. 

Here are the relevant parts of the logfiles from above:

```bash
...
# zwave-js: Ping failed on sleeping device
14:37:15.715 CNTRLR   [Node 013] ping failed: The node is asleep
14:37:15.715 CNTRLR » [Node 013] querying node info...
...
# zwave-js: NodeInfo stage completes (failed):
15:12:22.635 CNTRLR   [Node 013] querying the node info failed
15:12:22.643 CNTRLR   [Node 013] Interview stage completed: NodeInfo
15:12:22.643 CNTRLR   [Node 013] WakeUpCC: doing a complete interview...
15:12:22.644 CNTRLR » [Node 013] retrieving wakeup interval from the device...
...
# Button is pressed on the device:
2021-01-17 15:34:42.494 INFO ZWAVE: Node 13: value added: 113-0-Home Security-Sensor status => 2
2021-01-17 15:34:42.554 INFO ZWAVE: Node 13: metadata updated: 91-0-scene-001
2021-01-17 15:34:42.561 INFO ZWAVE: Node 13: value notification: 91-0-scene-001 0
...
# zwave-js signals that the node is now ready to be used (although no manufacturer id and product id is known):
15:59:30.756 CNTRLR   [Node 013] Interview completed
15:59:30.779 CNTRLR   [Node 013] The node is ready to be used
2021-01-17 15:59:30.542 INFO ZWAVE: Node 13: value added: 132-0-wakeUpInterval => 3600
2021-01-17 15:59:30.542 INFO ZWAVE: Node 13: value added: 132-0-controllerNodeId => 1
2021-01-17 15:59:30.743 INFO ZWAVE: Node 13: value updated: 132-0-wakeUpInterval 3600 => 3600
2021-01-17 15:59:30.745 INFO ZWAVE: Node 13: value updated: 132-0-controllerNodeId 1 => 1
2021-01-17 15:59:30.779 DEBUG GATEWAY: Publishing discovery: {
  type: 'sensor',
  object_id: 'scene_state_001_scene',
  discovery_payload: {
    state_topic: 'zwavejs2mqtt/nodeID_13/91/0/scene/001',
    value_template: '{{ value_json.value}}',
    json_attributes_topic: 'zwavejs2mqtt/nodeID_13/91/0/scene/001',
    device: {
      identifiers: [ 'zwavejs2mqtt_0xcb10ff7c_node13', [length]: 1 ],
      manufacturer: 'Unknown manufacturer undefined',
      model: 'undefined (Unknown product undefined)',
      name: 'nodeID_13',
      sw_version: '1.0.0-beta.0'
    },
    name: 'nodeID_13_scene_state_001_scene',
    unique_id: 'zwavejs2mqtt_0xcb10ff7c_13-91-0-scene-001'
  },
  discoveryTopic: 'sensor/nodeID_13/scene_state_001_scene/config',
  values: [ '91-0-scene-001', [length]: 1 ],
  persistent: false,
  ignoreDiscovery: false
}
2021-01-17 15:59:30.768 INFO ZWAVE: Node 13: value added 13-132-0-wakeUpInterval => 3600
2021-01-17 15:59:30.778 INFO ZWAVE: Node 13: value added 13-132-0-controllerNodeId => 1
# zwavejs2mqtt completes node initialization as "unknown manufacturer/product":
2021-01-17 15:59:30.779 INFO ZWAVE: Node 13 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
2021-01-17 15:59:30.780 INFO ZWAVE: Node 13: interview completed, all values are updated
2021-01-17 15:59:31.860 INFO ZWAVE: Node 13 is now asleep
...
# Manually trigger "Refresh info" for node 13 from zwavejs2mqtt and pressing Fibaro button 6x (for wakeup and send node info)
2021-01-17 19:19:29.797 INFO APP: Zwave api call: refreshInfo [ 13, [length]: 1 ]
2021-01-17 19:19:29.836 INFO ZWAVE: Success zwave api call refreshInfo
2021-01-17 19:19:38.790 INFO ZWAVE: Node 13 is now asleep
2021-01-17 19:19:44.271 INFO ZWAVE: Node 13 is now awake
# Here the manufacturerId, productType and productId are correctly updated:
2021-01-17 19:19:45.380 INFO ZWAVE: Node 13: value added: 114-0-manufacturerId => 271
2021-01-17 19:19:45.382 INFO ZWAVE: Node 13: value added: 114-0-productType => 3841
2021-01-17 19:19:45.383 INFO ZWAVE: Node 13: value added: 114-0-productId => 4096
# zwavejs2mqtt does not update manufacturer and product name in the UI and still shows it as "unknown"
...
```

**Comment by robertsLando** [comment]
@AlCalzone what I don't understand here is why the ready event is triggered if the node isn't really ready? At least based on the supposition of @ahochsteger seems that when the ready event is triggered we are missing the manufacturer product type and id CCs

**Comment by AlCalzone** [comment]
That's it:
```
# zwave-js: Ping failed on sleeping device
14:37:15.715 CNTRLR   [Node 013] ping failed: The node is asleep
14:37:15.715 CNTRLR » [Node 013] querying node info...
...
# zwave-js: NodeInfo stage completes (failed):
15:12:22.635 CNTRLR   [Node 013] querying the node info failed
15:12:22.643 CNTRLR   [Node 013] Interview stage completed: NodeInfo
```
Querying the node info fails for some reason, meaning we don't know which CCs are supported.
Because we don't know that, no CCs are queried except WakeUp CC (which is mandatory for Battery-powered devices).
After that, the interview is quickly finished, emitting the `"ready"` event.

**Comment by AlCalzone** [comment]
So with the linked PR, we now abort the interview if requesting the node info fails.

**Comment by bdbogjoe** [comment]
here my logs from linux using npm

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826810/zwavejs2mqtt.log)
[zwavejs_3944233.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826811/zwavejs_3944233.log)

the same devices are well found from raspberry but here there is in logs : 
`
2021-01-17 21:45:12.420 INFO ZWAVE: Node 6 ready: Unknown manufacturer undefined - Unknown product undefined (Unknown)
`

here the logs from the raspberry : 

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826823/zwavejs2mqtt.log)
[zwavejs_5363.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826824/zwavejs_5363.log)


`
INFO ZWAVE: Node 6 ready: Fibargroup - FGBS222 (Smart Implant)
INFO ZWAVE: Node 7 ready: Fibargroup - FGS223 (Double Switch 2)
`

**Comment by AlCalzone** [comment]
@bdbogjoe the difference is that log one shows a restart from cache and log two a complete interview, including manufacturer info.
In the first one, that info should already be in the cache, but I can't tell without those files.

**Comment by bdbogjoe** [comment]
should i sent the log after full cleanup for the first try ?

**Comment by bdbogjoe** [comment]
here the logs, now works fine with this branch !

[zwavejs2mqtt.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826906/zwavejs2mqtt.log)
[zwavejs_3984622.log](https://github.com/zwave-js/zwavejs2mqtt/files/5826907/zwavejs_3984622.log)

[e86a487a.zip](https://github.com/zwave-js/zwavejs2mqtt/files/5826910/e86a487a.zip)

**Comment by AlCalzone** [comment]
Hm, probably was a fluke. If the issue persists after a refreshInfo, let me know.

**Pull request merged**
