### PR TITLE
[feat] Add (more) directions to access the UI from within HA 

### PR DESCRIPTION
**Pull request by blhoward2**
Follow-up to #205 

A user asked for additional detail regarding the lovelace change.

### CODE REVIEW

**Comment by blhoward2** [comment]
@zwave-js-bot fix lint

**Comment by blhoward2** [comment]
You're my new best friend bot...lol.

**Comment by chilicheech** [comment]
This looks great, thanks @blhoward2

**Review by robertsLando — APPROVED** [review]
LGTM

**Pull request merged**
