### PR TITLE
chore(docker): updated docker-compose.yml to add TZ variable

### PR DESCRIPTION
**Pull request by scyto**
added TZ env var to docker-compose file as hint to new folks asking about timestamp in logs

### CODE REVIEW

**Review by BluGeni — COMMENTED** [review]
Line 9 there already is an environment declaration. Might want to move your TZ comment to below that.

**Comment by scyto** [comment]
> Line 9 there already is an environment declaration. Might want to move your TZ comment to below that.

done, when did that new secrets env var sneak in :-)

**Comment by robertsLando** [comment]
@scyto Could you add that also to docker readme? it contains a copy of that copose file

**Comment by scyto** [comment]
yes, will do it today or tomorrow

**Comment by scyto** [comment]
@robertsLando amended readme, sorry took so long.

**Review by robertsLando — APPROVED** [review]

**Pull request merged**
