### PR TITLE
fix: barrier operator hass replace barrier states with integers

### LINKED ISSUE #555: Cover state is not being interpreted correctly in Home Assistant
Before submitting a bug please read: <https://zwave-js.github.io/zwavejs2mqtt/#/troubleshooting/bug_report>

### Version

Build/Run method

- [ ] Docker
- [ ] PKG
- [x] Manually built (git clone - npm install - npm run build )

zwavejs2mqtt version: `1.1.1.5bba9ae`
zwavejs version: `6.1.3-0-pr-1337-77c6cad`

### Describe the bug

While new cover feature works correctly from zwavejs2mqtt control panel, cover is showing an "unknown" state in Home Assistant and cannot be controlled.

### To Reproduce

1. Add cover device in zwavejs2mqtt with Home Assistant discovery enabled
2. Check that device shows up in Home Assistant (in my case, it's `home_garagedoor`)
3. From the Developer Tools, check the status of the cover (in my case, `cover.home_garagedoor_barrier_state`)
4. Status is "unknown"

### Expected behavior

Status should be Open or Closed with the ability to open/close the garage door.

### Additional context

From MQTT: `cover/Home-GarageDoor/barrier_state/config`:
```
{
	"command_topic": "zwave/Home/34/102/0/targetState/set",
	"state_topic": "zwave/Home/34/102/0/currentState",
	"value_template": "{{ value_json.value }}",
	"device_class": "garage",
	"payload_open": "Opened",
	"payload_close": "Closed",
	"payload_stop": "Stopped",
	"state_open": "Opened",
	"state_opening": "Opening",
	"state_closed": "Closed",
	"state_closing": "Closing",
	"device": {
		"identifiers": [
			"zwavejs2mqtt_0xca51aa0a_node34"
		],
		"manufacturer": "Nortek Security & Control LLC",
		"model": "Garage Door Controller (NGD00Z-4)",
		"name": "Home-GarageDoor",
		"sw_version": "2.1"
	},
	"name": "Home-GarageDoor_barrier_state",
	"unique_id": "zwavejs2mqtt_0xca51aa0a_34-102-0-currentState"
}
```
From MQTT: `Home/34/102/0/currentState`:
```
{
	"id": "34-102-0-currentState",
	"nodeId": 34,
	"commandClass": 102,
	"commandClassName": "Barrier Operator",
	"endpoint": 0,
	"property": "currentState",
	"propertyName": "currentState",
	"type": "number",
	"readable": true,
	"writeable": false,
	"label": "Current Barrier State",
	"stateless": false,
	"min": 0,
	"max": 255,
	"list": true,
	"states": [
		{
			"text": "Closed",
			"value": 0
		},
		{
			"text": "Closing",
			"value": 252
		},
		{
			"text": "Stopped",
			"value": 253
		},
		{
			"text": "Opening",
			"value": 254
		},
		{
			"text": "Open",
			"value": 255
		}
	],
	"value": 0,
	"isCurrentValue": true,
	"targetValue": "102-0-targetState",
	"lastUpdate": 1613050943752
}
```
Home Assistant version 2021.1.5 shows:
image

### PR DESCRIPTION
**Pull request by billiaz**
This PR tries to fix #555 
We need to test it before implementing it
@ratsputin can you try it?

### CODE REVIEW

**Review by robertsLando — APPROVED** [review]
From a code side, LGTM

**Comment by robertsLando** [comment]
@billiaz can we merge this?

**Comment by aretakisv** [comment]
no, there is a small issue I want to discuss with reporter of this! as it is a state we need to cover.
I will try to fix this too

**Comment by billiaz** [comment]
@robertsLando merged fresh master branch to this project

**Comment by robertsLando** [comment]
@billiaz Is this ready to be merged?

**Comment by billiaz** [comment]
I think yes. But I want to be sure for one details about the unknown state. Looking on possible "if" statement
I need 5 more minutes :)

**Comment by billiaz** [comment]
@robertsLando it is good for now

**Comment by robertsLando** [comment]
Tell me when it's ready to merge so :)

**Comment by robertsLando** [comment]
@billiaz ?

**Comment by billiaz** [comment]
Updated from Master, ready to be merged back to master after this, if no problems found in linting

**Comment by kpine** [comment]
How does the `payload_stop` command work?

The Barrier Operator CC Set command does not have a stop value, only open and close. My understanding was that the only way to stop a cover is issuing an open command when it's in the closing state.

**Comment by robertsLando** [comment]
@billiaz ?

**Comment by billiaz** [comment]
Hmm that becomes tricky.... @robertsLando @kpine 

One thought @robertsLando is to program a function in Zwavejs2mqtt, if this is the state and a stop command comes in, to execute the proper in driver... 
I need to think that

**Comment by robertsLando** [comment]
@billiaz multilevel CC has startLevelChange and stopLevelChange, in writeValue function I have handle them by checking if the CC is multilevel switch and the payload is `start` or `stop`, we could easily do the same here for barrier operator if it provides such functions, But you need to change the payload in the template here. Maybe by using set command? https://zwave-js.github.io/node-zwave-js/#/api/CCs/BarrierOperator?id=set

**Comment by kpine** [comment]
Well, it was more of a question. I implemented the Barrier Operator support for the cover platform in Home Assistant, and from looking at the z-wave specs and the node-zwave-js API, there is no Stop command, so I did not implement support for it. The spec also shows that you stop the cover only when it's closing, using an Open command. I was following the work here and noticed that you added the `payload_stop` discovery field, which I believe would allow HA to send a "Stop" command? I was wondering if that actually worked or not, because I don't see how it would.

image

**Pull request merged**
