### PR TITLE
fix: don't query neighbors on node ready event

### PR DESCRIPTION
**Pull request by robertsLando**
CC @AlCalzone. Fixes https://github.com/zwave-js/node-zwave-js/issues/2493

### CODE REVIEW

**Comment by AlCalzone** [comment]
You still refresh this when opening the map, right?

**Comment by robertsLando** [comment]
@AlCalzone Yep

**Comment by ualex73** [comment]
Just a question :-) There is a corruption of the cache file, caused by the neighhors query - the "fix" seems to change the query moment only. Does this really fix any possible cache corruption?

**Comment by robertsLando** [comment]
@ualex73 Based on what @AlCalzone said to me seems the problem is that I actually query neighbors when nodes are ready. In large networks this could cause problems as 

> the routing table is in the so-called NVM. Accessing that requires to stop the stick from sending/receiving while you do it (@AlCalzone)

In poor words requesting neighbors could cause congestion on the controller expecially if it is doing interviews on startup or other things, with this fix neighbors are only refreshed when network graph is shown on the ui (or the api `refreshNeighgbors` is called).

Another fix in future will be to turn off the radio before query neighbors and turn on it once done. This needs https://github.com/zwave-js/node-zwave-js/pull/2636

**Comment by ualex73** [comment]
Ok, I understand it would lock up the stick if such query happens at start-up. Only if such situation happens (e.g. no response from stick during start-up), then it should never corrupt the cache, which still could happen? Just with this fix, the change will go towards to <1%.

**Comment by robertsLando** [comment]
I think the problem is not the corrupted cache but I  let speak @AlCalzone about this. It's not a complete fix but could save some corruptions

**Comment by AlCalzone** [comment]
Normally during the startup, listening nodes are pinged to figure out if they are alive or dead, then they are marked "ready". zwavejs2mqtt uses this event to display the information we already know, but that doesn't happen if the stick gets stuck before that. This looks like a corrupted cache, but the info is just not shown.

**Comment by robertsLando** [comment]
Second part in #1283

**Pull request merged**
