### PR TITLE
fix: lazy load not working behind a proxy

### LINKED ISSUE #2568: X-External-Path ignored
### Checklist

- [ ]  I am not using Home Assistant. Or: a developer has told me to come here.
- [ ] I have checked the troubleshooting section and my problem is not described there.
- [ ] I have read the changelog and my problem is not mentioned there.

### Deploy method

Manually built (git clone - yarn build - yarn install

### Zwavejs2Mqtt version

6.15.1

### ZwaveJS version

no relevant

### Describe the bug

Regression after v6.15.0 release caused this (described in #2564 as well).

CleanShot 2022-08-04 at 16 16 15

With the following console messages:

CleanShot 2022-08-04 at 16 16 49

However, that was fixed in 935a18d977d63087f4dcc6c6fd5a9d4e815e1e41, released with v6.15.1, which currently results in:

CleanShot 2022-08-04 at 16 17 34

Console messages:

CleanShot 2022-08-04 at 16 17 58

It seems that `X-External-Path` is completely ignored at this point.

### To Reproduce

Host Z-Wave JS behind a reverse proxy in a subfolder, passing the `X-External-Path` header, `FORCE_DISABLE_SSL=true`.

### Expected behavior

A UI.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2568

### CODE REVIEW

**Comment by robertsLando** [comment]
Seems icons are still not working BTW 😞

**Comment by robertsLando** [comment]
@franck could you give this a try?

**Comment by frenck** [comment]
image

🤘 tested against 42b727c0df921d79fecc105f6804be7e0fb1243d

**Comment by franck** [comment]
wrong franck 😘

Le ven. 5 août 2022 à 14:39, Daniel Lando ***@***.***> a
écrit :

**Comment by frenck** [comment]
Ooh boy! I hope that doesn't happen too often @franck!
Anyways there follow name person, you have a beautiful name 😄 ❤️

**Comment by robertsLando** [comment]
> wrong franck

Yeah sorry 😆

**Comment by robertsLando** [comment]
@frenck FYI I also added a nginx setup to try this out next time I put my hands on webpack stuff to check I didn't break anything https://github.com/zwave-js/zwavejs2mqtt/tree/master/docker/nginx

**Comment by frenck** [comment]
Yeah, I noticed 👍 

Thanks for jumping on it so quick ❤️

**Comment by robertsLando** [comment]
Release 6.15.2 is out 🚀

**Pull request merged**
