### PR TITLE
feat: zwavejs@6.5.0 and nodeFilter setting support

### PR DESCRIPTION
**Pull request by robertsLando**

### CODE REVIEW

**Comment by mgriffin13** [comment]
I tried the `:dev` image, but it doesn't look like it supports multiple nodes. Is that intentional? like, i can set the `Log Nodes` field to `5`, but I cannot set it to `5, 21`. I also tried `[5, 21]` and `5,21` (no space)

**Comment by robertsLando** [comment]
you have to insert the node number and press enter

**Comment by robertsLando** [comment]
Schermata da 2021-02-24 16-29-10

**Comment by mgriffin13** [comment]
aha, perfect. thank you for the clarification

**Pull request merged**
