### PR TITLE
fix: stop RF when requesting neighbors

### PR DESCRIPTION
**Pull request by robertsLando**
Reference: https://github.com/zwave-js/node-zwave-js/issues/2493
Introduced by: https://github.com/zwave-js/node-zwave-js/pull/2636

### CODE REVIEW

**Comment by AlCalzone** [comment]
Do you have some kind of safeguard in place so this method isn't invoked too often? Especially overlapping calls should be avoided, but I think you should take care not to turn the radio off too often.

**Comment by robertsLando** [comment]
@AlCalzone Actually nope but I can add it, What could be a safe time between calls of this method?

10 seconds?

**Comment by AlCalzone** [comment]
I mean the neighbors shouldn't change that often and you're caching them anyways. I dunno - maybe max. once per minute and reset the lock on the call when a node was added or removed?

**Comment by ualex73** [comment]
Question: if you turn off the radio and you restart ZwaveJS, does the stick automatically start receiving again? Just curious if a "problem" (app dies?) happen when turning the radio off and it should automatically recover with a restart.

**Comment by AlCalzone** [comment]
I'm not sure tbh. Guess we have to try 😅

**Pull request merged**
