### PR TITLE
fix: icons are no longer displayed after css-loader major upgrade

### LINKED ISSUE #1728: [bug] The icons are no longer displayed
### Version

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [x] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt: 5.6.1.9daf577
zwave-js: 8.3.1

### Describe the bug

The icons are no longer displayed

### To Reproduce

Show zwavejs2mqtt

### PR DESCRIPTION
**Pull request by ahochsteger**
This reverts commit 706343400b98c75aed43a9aebe93c0fd3ed9600a.

Fixes #1728

### CODE REVIEW

**Comment by firstof9** [comment]
You also need to fix your commit message.

**Comment by ahochsteger** [comment]
> You also need to fix your commit message.

@firstof9, I've seen the complaint about "Semantic PR title / commit message" and then already changed the title of the PR to comply to conventional commits.
Shouldn't this be enough?

**Comment by firstof9** [comment]
Nope your commit message also needs to follow suit.

**Comment by ahochsteger** [comment]
> Nope your commit message also needs to follow suit.

@firstof9, done.

**Comment by firstof9** [comment]
Cheers!

**Comment by blhoward2** [comment]
@ahochsteger you can also try `zwave-js-bot rename commit`. It only matters for single commit PRs.

**Review by robertsLando — APPROVED** [review]
Ok, will try to fix the breaking changes once I come back. Thanks!

**Comment by ahochsteger** [comment]
@blhoward2, thanks, I was not aware, that for single-commit PRs the real commit message must be changed. I thought the PR title can be used as well for the merge commit.
I've done so with `git commit --amend` and `git push --force` (see this [event](https://github.com/zwave-js/zwavejs2mqtt/pull/1729#event-5357463560)) but I am unsure if this is really the way it should be done?
Usually I prevent force-pushing to Github ...

**Comment by blhoward2** [comment]
I'm not sure there is a right way. I've seen people force push. I've seen others push empty commits. I'm honestly not the expert because rarely do I do anything in one commit. 😬 We frequently use the bot to fix it for submitters.

**Pull request merged**
